/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(buffer_corrector.h) */
/* BINDTOOL_HEADER_FILE_HASH(5b9c4d1adea91b1a5c80098044384ff6) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/buffer_corrector.h>
// pydoc.h is automatically generated in the build directory
#include <buffer_corrector_pydoc.h>

void bind_buffer_corrector(py::module &m) {

  using buffer_corrector = ::gr::harmonia::buffer_corrector;

  py::class_<buffer_corrector, gr::block, gr::basic_block,
             std::shared_ptr<buffer_corrector>>(m, "buffer_corrector",
                                                D(buffer_corrector))

      .def(py::init(&buffer_corrector::make), py::arg("max_buffer_size"),
           D(buffer_corrector, make))

      ;
}
