/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(compensation.h) */
/* BINDTOOL_HEADER_FILE_HASH(f3e529725db546e4b981117752709338) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/compensation.h>
// pydoc.h is automatically generated in the build directory
#include <compensation_pydoc.h>

void bind_compensation(py::module &m) {

  using compensation = ::gr::harmonia::compensation;

  py::class_<compensation, gr::block, gr::basic_block,
             std::shared_ptr<compensation>>(m, "compensation", D(compensation))

      .def(py::init(&compensation::make), py::arg("center_freq"),
           py::arg("samp_rate"), py::arg("sdr_id"), D(compensation, make))

      ;
}
