/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(device.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(192020a5d0d980eedf3fa1d3a2f60b2c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/device.h>
// pydoc.h is automatically generated in the build directory
#include <device_pydoc.h>

void bind_device(py::module& m)
{

    using Device = ::gr::harmonia::Device;

    py::class_<Device, std::shared_ptr<Device>> device_class(m, "Device", D(Device));

    device_class.def(py::init<>(), D(Device, Device, 0));
    device_class.def(py::init<gr::harmonia::Device const&>(), py::arg("arg0"), D(Device, Device, 1));

    py::enum_<gr::harmonia::Device::Backend>(device_class, "Backend")
        .value("DEFAULT", gr::harmonia::Device::DEFAULT)
        .value("CPU", gr::harmonia::Device::CPU)
        .value("CUDA", gr::harmonia::Device::CUDA)
        .value("OPENCL", gr::harmonia::Device::OPENCL) // 999
        .export_values();
    py::implicitly_convertible<int, gr::harmonia::Device::Backend>();
}
