/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(LFM_src.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ea17a3918d9425a611d2f41b33701a03) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/LFM_src.h>
// pydoc.h is automatically generated in the build directory
#include <LFM_src_pydoc.h>

void bind_LFM_src(py::module &m) {

  using LFM_src = ::gr::harmonia::LFM_src;

  py::class_<LFM_src, gr::block, gr::basic_block, std::shared_ptr<LFM_src>>(
      m, "LFM_src", D(LFM_src))

      .def(py::init(&LFM_src::make), py::arg("bandwidth"),
           py::arg("start_freq"), py::arg("center_freq"),
           py::arg("pulse_width"), py::arg("pulse_width2"),
           py::arg("samp_rate"), py::arg("prf"), py::arg("zeropad"),
           py::arg("sdr_id"), D(LFM_src, make))

      .def("init_meta_dict", &LFM_src::init_meta_dict, py::arg("bandwidth_key"),
           py::arg("duration_key"), py::arg("sample_rate_key"),
           py::arg("label_key"), py::arg("prf_key"), D(LFM_src, init_meta_dict))

      ;
}
