/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_complex_to_mag.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(83838fdc5347eed4b4b35887f3618aed)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/pdu_complex_to_mag.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_complex_to_mag_pydoc.h>

void bind_pdu_complex_to_mag(py::module& m)
{

    using pdu_complex_to_mag = ::gr::harmonia::pdu_complex_to_mag;


    py::class_<pdu_complex_to_mag,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_complex_to_mag>>(
        m, "pdu_complex_to_mag", D(pdu_complex_to_mag))

        .def(py::init(&pdu_complex_to_mag::make), D(pdu_complex_to_mag, make))


        ;
}
