/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_fft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2423b31bace4ca753bae363fc9866cdc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/pdu_fft.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_fft_pydoc.h>

void bind_pdu_fft(py::module& m)
{

    using pdu_fft = ::gr::harmonia::pdu_fft;


    py::class_<pdu_fft, gr::block, gr::basic_block, std::shared_ptr<pdu_fft>>(
        m, "pdu_fft", D(pdu_fft))

        .def(py::init(&pdu_fft::make), py::arg("nfft"), D(pdu_fft, make))


        .def("set_msg_queue_depth",
             &pdu_fft::set_msg_queue_depth,
             py::arg("arg0"),
             D(pdu_fft, set_msg_queue_depth))


        .def("set_backend",
             &pdu_fft::set_backend,
             py::arg("arg0"),
             D(pdu_fft, set_backend))


        .def("set_metadata_keys",
             &pdu_fft::set_metadata_keys,
             py::arg("fft_size_key"),
             D(pdu_fft, set_metadata_keys))

        ;
}
