/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(SDR_tagger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fa725b0ac33db0d108cdbc99ce567275) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/SDR_tagger.h>
// pydoc.h is automatically generated in the build directory
#include <SDR_tagger_pydoc.h>

void bind_SDR_tagger(py::module &m) {

  using SDR_tagger = ::gr::harmonia::SDR_tagger;

  py::class_<SDR_tagger, gr::block, gr::basic_block,
             std::shared_ptr<SDR_tagger>>(m, "SDR_tagger", D(SDR_tagger))

      .def(py::init(&SDR_tagger::make), py::arg("sdr_num_key"),
           D(SDR_tagger, make))

      ;
}
