/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(single_tone_src.h) */
/* BINDTOOL_HEADER_FILE_HASH(f31a62a84a3febc452442dff4dd09cdb) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/single_tone_src.h>
// pydoc.h is automatically generated in the build directory
#include <single_tone_src_pydoc.h>

void bind_single_tone_src(py::module &m) {

  using single_tone_src = ::gr::harmonia::single_tone_src;

  py::class_<single_tone_src, gr::block, gr::basic_block,
             std::shared_ptr<single_tone_src>>(m, "single_tone_src",
                                               D(single_tone_src))

      .def(py::init(&single_tone_src::make), py::arg("frequency"),
           py::arg("center_freq"), py::arg("phase"), py::arg("pulse_width"),
           py::arg("samp_rate"), py::arg("prf"), py::arg("max_buffer_size"),
           py::arg("sdr_id"), D(single_tone_src, make))

      .def("init_meta_dict", &single_tone_src::init_meta_dict,
           py::arg("frequency_key"), py::arg("phase_key"),
           py::arg("duration_key"), py::arg("sample_rate_key"),
           py::arg("label_key"), py::arg("prf_key"),
           D(single_tone_src, init_meta_dict))

      ;
}
