/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(time_pk_est.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(37b5000923f396db0ce8610814fa5f28) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/time_pk_est.h>
// pydoc.h is automatically generated in the build directory
#include <time_pk_est_pydoc.h>

void bind_time_pk_est(py::module &m) {

  using time_pk_est = ::gr::harmonia::time_pk_est;

  py::class_<time_pk_est, gr::block, gr::basic_block,
             std::shared_ptr<time_pk_est>>(m, "time_pk_est", D(time_pk_est))

      .def(py::init(&time_pk_est::make), py::arg("nfft"), py::arg("samp_rate"),
           py::arg("bandwidth"), py::arg("NLLS_iter"), py::arg("NLLS_pts"),
           D(time_pk_est, make))

      .def("set_msg_queue_depth", &time_pk_est::set_msg_queue_depth,
           py::arg("depth"), D(time_pk_est, set_msg_queue_depth))

      .def("set_backend", &time_pk_est::set_backend, py::arg("arg0"),
           D(time_pk_est, set_backend))

      .def("set_metadata_keys", &time_pk_est::set_metadata_keys,
           D(time_pk_est, set_metadata_keys))

      ;
}
