/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(usrp_radar_tdma.h) */
/* BINDTOOL_HEADER_FILE_HASH(8caa2e210d3cfd33fb82656ed6d35684) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/usrp_radar_tdma.h>
// pydoc.h is automatically generated in the build directory
#include <usrp_radar_tdma_pydoc.h>

void bind_usrp_radar_tdma(py::module &m) {

  using usrp_radar_tdma = ::gr::harmonia::usrp_radar_tdma;

  py::class_<usrp_radar_tdma, gr::block, gr::basic_block,
             std::shared_ptr<usrp_radar_tdma>>(m, "usrp_radar_tdma",
                                               D(usrp_radar_tdma))

      .def(py::init(&usrp_radar_tdma::make), py::arg("args"),
           py::arg("sdr_rate"), py::arg("sdr_freq"), py::arg("sdr_gain"),
           py::arg("sdr_id"), py::arg("start_delay"), py::arg("cap_length"),
           py::arg("cap_length2"), py::arg("wait_time"), py::arg("TDMA_time"),
           py::arg("TDMA_time2"), D(usrp_radar_tdma, make))

      ;
}
