/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(usrp_radar_tx.h) */
/* BINDTOOL_HEADER_FILE_HASH(ba2b397734f930edca415d7fee78714c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/usrp_radar_tx.h>
// pydoc.h is automatically generated in the build directory
#include <usrp_radar_tx_pydoc.h>

void bind_usrp_radar_tx(py::module &m) {

  using usrp_radar_tx = ::gr::harmonia::usrp_radar_tx;

  py::class_<usrp_radar_tx, gr::block, gr::basic_block,
             std::shared_ptr<usrp_radar_tx>>(m, "usrp_radar_tx",
                                             D(usrp_radar_tx))

      .def(py::init(&usrp_radar_tx::make), py::arg("args_tx"),
           py::arg("tx_rate"), py::arg("tx_freq"), py::arg("tx_gain"),
           py::arg("start_delay"), py::arg("elevate_priority"),
           py::arg("verbose"), D(usrp_radar_tx, make))

      .def("set_metadata_keys", &usrp_radar_tx::set_metadata_keys,
           py::arg("tx_freq_key"), py::arg("sample_start_key"),
           py::arg("prf_key"), D(usrp_radar_tx, set_metadata_keys))

      ;
}
