/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(usrp_radar_rx.h) */
/* BINDTOOL_HEADER_FILE_HASH(33fdcba0b67bf1d4d5f68a8421333ba2) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/harmonia/usrp_radar_rx.h>
// pydoc.h is automatically generated in the build directory
#include <usrp_radar_rx_pydoc.h>

void bind_usrp_radar_rx(py::module &m) {

  using usrp_radar_rx = ::gr::harmonia::usrp_radar_rx;

  py::class_<usrp_radar_rx, gr::block, gr::basic_block,
             std::shared_ptr<usrp_radar_rx>>(m, "usrp_radar_rx",
                                             D(usrp_radar_rx))

      .def(py::init(&usrp_radar_rx::make), py::arg("args_rx"),
           py::arg("rx_rate"), py::arg("rx_freq"), py::arg("rx_gain"),
           py::arg("start_delay"), py::arg("elevate_priority"),
           py::arg("verbose"), D(usrp_radar_rx, make))

      .def("set_metadata_keys", &usrp_radar_rx::set_metadata_keys,
           py::arg("rx_freq_key"), py::arg("sample_start_key"),
           py::arg("prf_key"), D(usrp_radar_rx, set_metadata_keys))

      ;
}
